#??TomCat?????
server:
  port: 8080

spring:
  application:
    name:
      SmartImage_backend
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smart_image?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 12345
  data:
    redis:
      host: localhost
      port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yunchuan.smartimage_backend.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

alioss:
    access-key-id: LTAI5tQR1DCR4xsdN3E4ySJ8
    access-key-secret: BLtkCVoUl2Pmpn8x17PBa6kigdYkYb
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: smart-image-1